# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  name: Test
  inputs:
    command: 'test'
#    arguments: ' /p:CollectCoverage=true  /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit*]*%2c[Scriban]*%2c[*UnitTests*]*" '
    arguments: ' /p:CollectCoverage=true  /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)\TestResults\Coverage\  /p:Exclude="[xunit*]*%2c[Scriban]*%2c[*UnitTests*]*" '

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    versioningScheme: 'byPrereleaseNumber'
    requestedMajorVersion: '0'
    requestedMinorVersion: '1'

- task: PublishPipelineArtifact@0
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    #summaryFileLocation: '$(Build.SourcesDirectory)\**\coverage.cobertura.xml'
    summaryFileLocation: '$(Build.SourcesDirectory)\TestResults\Coverage\coverage.cobertura.xml'
    